name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn prepack
